CFLAGS += -mcpu=cortex-m7 -mlittle-endian -mfloat-abi=hard -mfpu=fpv5-sp-d16
CFLAGS += -include boards/$(BOARD)/include/stm32f722xx.h
LDFLAGS += -mcpu=cortex-m7 -mlittle-endian -mfloat-abi=hard -mfpu=fpv5-sp-d16
LDFLAGS += -L boards/$(BOARD)/ldscripts -T stm32f722ze.ld

## Specific flags for STM32F722ZE
JLINK_DEVICE := STM32F722ZE
